package com.njupt.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ServiceService service = new ServiceService();
 * ServiceDelegate portType = service.getServicePort();
 * portType.getPermission(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ServiceService", targetNamespace = "http://service.njupt.com/", wsdlLocation = "http://localhost:8080/IoT_Management_WebService/ServicePort?wsdl")
public class ServiceService extends Service {

	private final static URL SERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.njupt.service.ServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.njupt.service.ServiceService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/IoT_Management_WebService/ServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/IoT_Management_WebService/ServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICESERVICE_WSDL_LOCATION = url;
	}

	public ServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ServiceService() {
		super(SERVICESERVICE_WSDL_LOCATION, new QName(
				"http://service.njupt.com/", "ServiceService"));
	}

	/**
	 * 
	 * @return returns ServiceDelegate
	 */
	@WebEndpoint(name = "ServicePort")
	public ServiceDelegate getServicePort() {
		return super.getPort(new QName("http://service.njupt.com/",
				"ServicePort"), ServiceDelegate.class);
	}

}
