package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DaoDelegate", targetNamespace = "http://dao.ws_cxf_spring.njupt.com/")
public interface DaoDelegate {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sayHello", targetNamespace = "http://dao.ws_cxf_spring.njupt.com/", className = "client.SayHello")
	@ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://dao.ws_cxf_spring.njupt.com/", className = "client.SayHelloResponse")
	public String sayHello();

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertstudent", targetNamespace = "http://dao.ws_cxf_spring.njupt.com/", className = "client.Insertstudent")
	@ResponseWrapper(localName = "insertstudentResponse", targetNamespace = "http://dao.ws_cxf_spring.njupt.com/", className = "client.InsertstudentResponse")
	public int insertstudent(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getStudentnamebyID", targetNamespace = "http://dao.ws_cxf_spring.njupt.com/", className = "client.GetStudentnamebyID")
	@ResponseWrapper(localName = "getStudentnamebyIDResponse", targetNamespace = "http://dao.ws_cxf_spring.njupt.com/", className = "client.GetStudentnamebyIDResponse")
	public String getStudentnamebyID(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
